CREATE TABLE Student (
SID INT IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR(50)
);
 
CREATE TABLE Department (
DID INT IDENTITY(1,1) PRIMARY KEY,
DeptName VARCHAR(50),
Location VARCHAR(50)
);

CREATE TABLE Course (
CID INT IDENTITY(1,1) PRIMARY KEY,
Title VARCHAR(50),
DID INT,
FOREIGN KEY (DID) REFERENCES Department(DID)
);

CREATE TABLE Instructor (
IID INT IDENTITY(1,1)  PRIMARY KEY,
Name VARCHAR(50),
Role VARCHAR(50),
DID INT,
FOREIGN KEY (DID) REFERENCES Department(DID)
);

CREATE TABLE Section (
SecID INT IDENTITY(1,1)  PRIMARY KEY,
Semester VARCHAR(100),
MaxCapacity INT,
TimeBlock VARCHAR(100),
RoomNumber INT,
CID INT,
IID INT,
FOREIGN KEY (CID) REFERENCES Course(CID),
FOREIGN KEY (IID) REFERENCES Instructor(IID)
);

CREATE TABLE Cart (
SID INT,
SecID INT,
PRIMARY KEY (SID, SecID),
FOREIGN KEY (SID) REFERENCES Student(SID),
FOREIGN KEY (SecID) REFERENCES Section(SecID)
);

CREATE TABLE Enrollment (
SID INT,
SecID INT,
PRIMARY KEY (SID, SecID),
FOREIGN KEY (SID) REFERENCES Student(SID),
FOREIGN KEY (SecID) REFERENCES Section(SecID)
);

CREATE TABLE Prereq (
CID INT,
PrereqID INT,
Title VARCHAR(50),
PRIMARY KEY (CID, PrereqID),
FOREIGN KEY (CID) REFERENCES Course(CID),
FOREIGN KEY (PrereqID) REFERENCES Course(CID)
);