INSERT INTO Instructor (InstructorId, Faculty, Rank, University) VALUES
(1, 'Science', 'Professor', 'MacEwan University'),
(2, 'Science', 'Associate Professor', 'SAIT'),
(3, 'Business', 'Sessional', 'NAIT'),
(4, 'Arts', 'Sessional', 'University of Calgary'),
(5, 'Arts', 'Head', 'University of Calgary'),
(6, 'Law', 'Professor', 'NorQuest College'),
(7, 'Science', 'Sessional', 'University of Alberta'),
(8, 'Arts', 'Associate Professor', 'SAIT'),
(9, 'Arts', 'Associate Professor', 'NorQuest College'),
(10, 'Law', 'Associate Professor', 'NAIT'),
(11, 'Law', 'Sessional', 'SAIT'),
(12, 'Arts', 'Head', 'NorQuest College'),
(13, 'Arts', 'Associate Professor', 'University of Calgary'),
(14, 'Law', 'Sessional', 'University of Alberta'),
(15, 'Business', 'Professor', 'University of Alberta'),
(16, 'Arts', 'Sessional', 'Mount Royal University'),
(17, 'Science', 'Sessional', 'University of Calgary'),
(18, 'Arts', 'Professor', 'NorQuest College'),
(19, 'Arts', 'Associate Professor', 'MacEwan University'),
(20, 'Business', 'Associate Professor', 'MacEwan University'),
(21, 'Business', 'Associate Professor', 'University of Alberta'),
(22, 'Law', 'Associate Professor', 'Bow Valley University'),
(23, 'Science', 'Head', 'Athabasca University'),
(24, 'Business', 'Sessional', 'NAIT'),
(25, 'Science', 'Sessional', 'NAIT'),
(26, 'Arts', 'Sessional', 'University of Calgary'),
(27, 'Law', 'Associate Professor', 'University of Calgary'),
(28, 'Science', 'Associate Professor', 'University of Alberta'),
(29, 'Business', 'Professor', 'NorQuest College'),
(30, 'Arts', 'Professor', 'Bow Valley University'),
(31, 'Business', 'Associate Professor', 'NorQuest College'),
(32, 'Law', 'Associate Professor', 'MacEwan University'),
(33, 'Law', 'Sessional', 'MacEwan University'),
(34, 'Arts', 'Professor', 'Bow Valley University'),
(35, 'Arts', 'Head', 'MacEwan University'),
(36, 'Business', 'Professor', 'NAIT'),
(37, 'Arts', 'Head', 'MacEwan University'),
(38, 'Law', 'Professor', 'University of Calgary'),
(39, 'Business', 'Head', 'University of Alberta'),
(40, 'Business', 'Sessional', 'MacEwan University'),
(41, 'Science', 'Sessional', 'NAIT'),
(42, 'Arts', 'Professor', 'Bow Valley University'),
(43, 'Science', 'Sessional', 'University of Calgary'),
(44, 'Arts', 'Sessional', 'NAIT'),
(45, 'Law', 'Professor', 'NorQuest College'),
(46, 'Science', 'Associate Professor', 'NAIT'),
(47, 'Science', 'Associate Professor', 'SAIT'),
(48, 'Law', 'Associate Professor', 'MacEwan University'),
(49, 'Business', 'Professor', 'MacEwan University'),
(50, 'Arts', 'Professor', 'SAIT'),
(51, 'Law', 'Professor', 'University of Calgary'),
(52, 'Business', 'Professor', 'NAIT'),
(53, 'Arts', 'Associate Professor', 'University of Calgary'),
(54, 'Business', 'Professor', 'NorQuest College'),
(55, 'Arts', 'Associate Professor', 'SAIT'),
(56, 'Business', 'Professor', 'NorQuest College'),
(57, 'Arts', 'Sessional', 'NAIT'),
(58, 'Science', 'Professor', 'Mount Royal University'),
(59, 'Arts', 'Associate Professor', 'NAIT'),
(60, 'Science', 'Sessional', 'Mount Royal University'),
(61, 'Law', 'Head', 'University of Calgary'),
(62, 'Law', 'Associate Professor', 'SAIT'),
(63, 'Law', 'Sessional', 'Mount Royal University'),
(64, 'Arts', 'Associate Professor', 'NAIT'),
(65, 'Law', 'Associate Professor', 'NAIT'),
(66, 'Business', 'Sessional', 'Athabasca University'),
(67, 'Business', 'Sessional', 'University of Alberta'),
(68, 'Arts', 'Professor', 'Athabasca University'),
(69, 'Law', 'Associate Professor', 'Athabasca University'),
(70, 'Business', 'Professor', 'University of Calgary'),
(71, 'Law', 'Professor', 'Bow Valley University'),
(72, 'Business', 'Professor', 'SAIT'),
(73, 'Business', 'Professor', 'Bow Valley University'),
(74, 'Science', 'Head', 'NAIT'),
(75, 'Science', 'Professor', 'Athabasca University'),
(76, 'Science', 'Associate Professor', 'SAIT'),
(77, 'Law', 'Professor', 'NorQuest College'),
(78, 'Law', 'Associate Professor', 'Bow Valley University'),
(79, 'Science', 'Sessional', 'University of Alberta'),
(80, 'Business', 'Associate Professor', 'University of Alberta'),
(81, 'Law', 'Professor', 'University of Alberta'),
(82, 'Science', 'Head', 'MacEwan University'),
(83, 'Business', 'Professor', 'Bow Valley University'),
(84, 'Science', 'Sessional', 'Bow Valley University'),
(85, 'Science', 'Associate Professor', 'Mount Royal University'),
(86, 'Business', 'Professor', 'University of Calgary'),
(87, 'Law', 'Professor', 'NorQuest College'),
(88, 'Arts', 'Sessional', 'Bow Valley University'),
(89, 'Business', 'Head', 'NorQuest College'),
(90, 'Arts', 'Professor', 'SAIT'),
(91, 'Law', 'Sessional', 'University of Alberta'),
(92, 'Arts', 'Head', 'Athabasca University'),
(93, 'Business', 'Associate Professor', 'NAIT'),
(94, 'Science', 'Head', 'Bow Valley University'),
(95, 'Business', 'Professor', 'NAIT'),
(96, 'Law', 'Associate Professor', 'University of Calgary'),
(97, 'Law', 'Associate Professor', 'NorQuest College'),
(98, 'Law', 'Professor', 'University of Alberta'),
(99, 'Business', 'Sessional', 'University of Alberta'),
(100, 'Science', 'Professor', 'Mount Royal University'),
(101, 'Law', 'Professor', 'NorQuest College'),
(102, 'Business', 'Professor', 'University of Alberta'),
(103, 'Science', 'Professor', 'Athabasca University'),
(104, 'Arts', 'Professor', 'Mount Royal University'),
(105, 'Law', 'Professor', 'University of Alberta'),
(106, 'Science', 'Sessional', 'Athabasca University'),
(107, 'Business', 'Professor', 'Mount Royal University'),
(108, 'Arts', 'Sessional', 'SAIT'),
(109, 'Arts', 'Professor', 'NAIT'),
(110, 'Business', 'Associate Professor', 'NAIT'),
(111, 'Arts', 'Sessional', 'Mount Royal University'),
(112, 'Law', 'Associate Professor', 'Athabasca University'),
(113, 'Science', 'Associate Professor', 'Bow Valley University'),
(114, 'Business', 'Sessional', 'University of Calgary'),
(115, 'Business', 'Associate Professor', 'MacEwan University'),
(116, 'Business', 'Associate Professor', 'MacEwan University'),
(117, 'Science', 'Sessional', 'MacEwan University'),
(118, 'Science', 'Sessional', 'University of Calgary'),
(119, 'Science', 'Professor', 'Bow Valley University'),
(120, 'Business', 'Sessional', 'NorQuest College'),
(121, 'Business', 'Associate Professor', 'Mount Royal University'),
(122, 'Law', 'Professor', 'NAIT'),
(123, 'Science', 'Sessional', 'University of Alberta'),
(124, 'Arts', 'Professor', 'Bow Valley University'),
(125, 'Business', 'Professor', 'University of Calgary'),
(126, 'Business', 'Professor', 'NorQuest College'),
(127, 'Law', 'Professor', 'SAIT'),
(128, 'Arts', 'Professor', 'University of Alberta'),
(129, 'Science', 'Associate Professor', 'Athabasca University'),
(130, 'Science', 'Associate Professor', 'NAIT'),
(131, 'Law', 'Professor', 'NAIT'),
(132, 'Law', 'Associate Professor', 'University of Calgary'),
(133, 'Business', 'Professor', 'University of Calgary'),
(134, 'Science', 'Sessional', 'MacEwan University'),
(135, 'Science', 'Associate Professor', 'NorQuest College'),
(136, 'Science', 'Sessional', 'Athabasca University'),
(137, 'Business', 'Professor', 'Bow Valley University'),
(138, 'Law', 'Professor', 'University of Calgary'),
(139, 'Arts', 'Associate Professor', 'MacEwan University'),
(140, 'Arts', 'Sessional', 'Bow Valley University'),
(141, 'Law', 'Professor', 'Athabasca University'),
(142, 'Science', 'Sessional', 'University of Calgary'),
(143, 'Business', 'Associate Professor', 'MacEwan University'),
(144, 'Business', 'Professor', 'NAIT'),
(145, 'Business', 'Sessional', 'SAIT'),
(146, 'Science', 'Sessional', 'NAIT'),
(147, 'Law', 'Sessional', 'Mount Royal University'),
(148, 'Law', 'Associate Professor', 'University of Alberta'),
(149, 'Business', 'Sessional', 'MacEwan University'),
(150, 'Arts', 'Professor', 'Athabasca University'),
(151, 'Business', 'Associate Professor', 'University of Calgary'),
(152, 'Business', 'Associate Professor', 'Bow Valley University'),
(153, 'Science', 'Associate Professor', 'Bow Valley University'),
(154, 'Arts', 'Professor', 'NorQuest College'),
(155, 'Arts', 'Professor', 'NAIT'),
(156, 'Science', 'Professor', 'University of Alberta'),
(157, 'Business', 'Professor', 'Mount Royal University'),
(158, 'Business', 'Professor', 'Bow Valley University'),
(159, 'Arts', 'Associate Professor', 'Bow Valley University'),
(160, 'Business', 'Associate Professor', 'University of Calgary'),
(161, 'Law', 'Sessional', 'Bow Valley University'),
(162, 'Science', 'Associate Professor', 'NorQuest College'),
(163, 'Arts', 'Sessional', 'University of Calgary'),
(164, 'Science', 'Associate Professor', 'MacEwan University'),
(165, 'Science', 'Sessional', 'University of Alberta'),
(166, 'Arts', 'Sessional', 'SAIT'),
(167, 'Business', 'Associate Professor', 'Bow Valley University'),
(168, 'Business', 'Associate Professor', 'University of Calgary'),
(169, 'Arts', 'Sessional', 'MacEwan University'),
(170, 'Arts', 'Professor', 'SAIT'),
(171, 'Business', 'Associate Professor', 'Mount Royal University'),
(172, 'Arts', 'Associate Professor', 'University of Alberta'),
(173, 'Science', 'Head', 'MacEwan University'),
(174, 'Business', 'Associate Professor', 'NorQuest College'),
(175, 'Science', 'Associate Professor', 'NorQuest College'),
(176, 'Law', 'Associate Professor', 'Bow Valley University'),
(177, 'Law', 'Associate Professor', 'NAIT'),
(178, 'Business', 'Professor', 'MacEwan University'),
(179, 'Law', 'Professor', 'SAIT'),
(180, 'Law', 'Professor', 'NAIT'),
(181, 'Business', 'Sessional', 'NAIT'),
(182, 'Law', 'Associate Professor', 'University of Alberta'),
(183, 'Business', 'Sessional', 'Mount Royal University'),
(184, 'Business', 'Associate Professor', 'University of Alberta'),
(185, 'Arts', 'Professor', 'Mount Royal University'),
(186, 'Science', 'Associate Professor', 'SAIT'),
(187, 'Law', 'Associate Professor', 'Mount Royal University'),
(188, 'Science', 'Sessional', 'NAIT'),
(189, 'Science', 'Associate Professor', 'SAIT'),
(190, 'Law', 'Sessional', 'University of Calgary'),
(191, 'Business', 'Professor', 'MacEwan University'),
(192, 'Law', 'Professor', 'University of Alberta'),
(193, 'Arts', 'Sessional', 'Mount Royal University'),
(194, 'Business', 'Professor', 'NorQuest College'),
(195, 'Business', 'Associate Professor', 'NAIT'),
(196, 'Law', 'Professor', 'SAIT'),
(197, 'Arts', 'Associate Professor', 'Athabasca University'),
(198, 'Law', 'Associate Professor', 'Bow Valley University'),
(199, 'Law', 'Sessional', 'University of Alberta'),
(200, 'Law', 'Sessional', 'University of Calgary'),
(201, 'Business', 'Sessional', 'NorQuest College'),
(202, 'Law', 'Professor', 'SAIT'),
(203, 'Arts', 'Professor', 'Bow Valley University'),
(204, 'Science', 'Sessional', 'MacEwan University'),
(205, 'Arts', 'Associate Professor', 'MacEwan University'),
(206, 'Science', 'Professor', 'Bow Valley University'),
(207, 'Business', 'Sessional', 'NAIT'),
(208, 'Arts', 'Associate Professor', 'University of Alberta'),
(209, 'Arts', 'Associate Professor', 'Mount Royal University'),
(210, 'Business', 'Professor', 'NAIT'),
(211, 'Arts', 'Associate Professor', 'Athabasca University'),
(212, 'Law', 'Sessional', 'Mount Royal University'),
(213, 'Arts', 'Sessional', 'NAIT'),
(214, 'Arts', 'Head', 'NAIT'),
(215, 'Science', 'Associate Professor', 'MacEwan University'),
(216, 'Science', 'Sessional', 'SAIT'),
(217, 'Arts', 'Professor', 'Mount Royal University'),
(218, 'Science', 'Professor', 'NorQuest College'),
(219, 'Science', 'Sessional', 'University of Alberta'),
(220, 'Science', 'Sessional', 'University of Alberta'),
(221, 'Science', 'Associate Professor', 'Athabasca University'),
(222, 'Business', 'Sessional', 'Athabasca University'),
(223, 'Law', 'Sessional', 'Mount Royal University'),
(224, 'Business', 'Associate Professor', 'Athabasca University'),
(225, 'Arts', 'Sessional', 'Mount Royal University'),
(226, 'Business', 'Associate Professor', 'NAIT'),
(227, 'Law', 'Professor', 'University of Alberta'),
(228, 'Business', 'Sessional', 'NorQuest College'),
(229, 'Business', 'Professor', 'University of Calgary'),
(230, 'Law', 'Sessional', 'NorQuest College'),
(231, 'Law', 'Professor', 'Bow Valley University'),
(232, 'Business', 'Professor', 'Athabasca University'),
(233, 'Business', 'Professor', 'University of Alberta'),
(234, 'Science', 'Sessional', 'NAIT'),
(235, 'Law', 'Professor', 'University of Calgary'),
(236, 'Law', 'Professor', 'NAIT'),
(237, 'Arts', 'Professor', 'Athabasca University'),
(238, 'Business', 'Associate Professor', 'SAIT'),
(239, 'Business', 'Sessional', 'Bow Valley University'),
(240, 'Business', 'Professor', 'Athabasca University'),
(241, 'Business', 'Associate Professor', 'University of Alberta'),
(242, 'Business', 'Professor', 'Athabasca University'),
(243, 'Arts', 'Sessional', 'Athabasca University'),
(244, 'Business', 'Associate Professor', 'Bow Valley University'),
(245, 'Law', 'Associate Professor', 'Bow Valley University'),
(246, 'Science', 'Associate Professor', 'Mount Royal University'),
(247, 'Science', 'Professor', 'University of Calgary'),
(248, 'Arts', 'Professor', 'NorQuest College'),
(249, 'Business', 'Associate Professor', 'MacEwan University'),
(250, 'Business', 'Associate Professor', 'SAIT'),
(251, 'Science', 'Associate Professor', 'Bow Valley University'),
(252, 'Law', 'Professor', 'University of Calgary'),
(253, 'Arts', 'Associate Professor', 'Bow Valley University'),
(254, 'Law', 'Associate Professor', 'Bow Valley University'),
(255, 'Business', 'Sessional', 'Athabasca University'),
(256, 'Arts', 'Professor', 'Mount Royal University'),
(257, 'Law', 'Sessional', 'Mount Royal University'),
(258, 'Law', 'Sessional', 'Bow Valley University'),
(259, 'Business', 'Professor', 'Bow Valley University'),
(260, 'Law', 'Sessional', 'SAIT'),
(261, 'Law', 'Associate Professor', 'NAIT'),
(262, 'Business', 'Sessional', 'Bow Valley University'),
(263, 'Arts', 'Associate Professor', 'MacEwan University'),
(264, 'Law', 'Sessional', 'SAIT'),
(265, 'Law', 'Sessional', 'University of Calgary'),
(266, 'Arts', 'Sessional', 'University of Alberta'),
(267, 'Business', 'Head', 'SAIT'),
(268, 'Law', 'Professor', 'Athabasca University'),
(269, 'Law', 'Professor', 'NorQuest College'),
(270, 'Law', 'Professor', 'University of Calgary'),
(271, 'Arts', 'Sessional', 'MacEwan University'),
(272, 'Arts', 'Sessional', 'Athabasca University'),
(273, 'Law', 'Associate Professor', 'Bow Valley University'),
(274, 'Business', 'Sessional', 'NorQuest College'),
(275, 'Business', 'Sessional', 'NAIT'),
(276, 'Business', 'Professor', 'MacEwan University'),
(277, 'Law', 'Sessional', 'University of Alberta'),
(278, 'Business', 'Sessional', 'University of Calgary'),
(279, 'Business', 'Sessional', 'University of Calgary'),
(280, 'Science', 'Sessional', 'NAIT'),
(281, 'Science', 'Professor', 'MacEwan University'),
(282, 'Law', 'Professor', 'NAIT'),
(283, 'Business', 'Sessional', 'Bow Valley University'),
(284, 'Arts', 'Associate Professor', 'NorQuest College'),
(285, 'Science', 'Head', 'Athabasca University'),
(286, 'Law', 'Associate Professor', 'University of Calgary'),
(287, 'Business', 'Associate Professor', 'Bow Valley University'),
(288, 'Business', 'Professor', 'SAIT'),
(289, 'Science', 'Sessional', 'NAIT'),
(290, 'Law', 'Sessional', 'Athabasca University'),
(291, 'Science', 'Professor', 'NAIT'),
(292, 'Arts', 'Associate Professor', 'NorQuest College'),
(293, 'Science', 'Associate Professor', 'NAIT'),
(294, 'Arts', 'Professor', 'Athabasca University'),
(295, 'Law', 'Sessional', 'SAIT'),
(296, 'Science', 'Professor', 'Mount Royal University'),
(297, 'Arts', 'Professor', 'Athabasca University'),
(298, 'Arts', 'Associate Professor', 'University of Alberta'),
(299, 'Arts', 'Professor', 'Bow Valley University'),
(300, 'Science', 'Professor', 'Bow Valley University'),
(301, 'Business', 'Sessional', 'University of Alberta'),
(302, 'Arts', 'Professor', 'MacEwan University'),
(303, 'Law', 'Associate Professor', 'Mount Royal University'),
(304, 'Business', 'Professor', 'Athabasca University'),
(305, 'Science', 'Associate Professor', 'NorQuest College'),
(306, 'Arts', 'Associate Professor', 'Mount Royal University'),
(307, 'Science', 'Professor', 'University of Calgary'),
(308, 'Science', 'Sessional', 'NAIT'),
(309, 'Business', 'Associate Professor', 'NorQuest College'),
(310, 'Arts', 'Associate Professor', 'University of Calgary'),
(311, 'Law', 'Sessional', 'Mount Royal University'),
(312, 'Science', 'Sessional', 'NorQuest College'),
(313, 'Science', 'Professor', 'University of Alberta'),
(314, 'Business', 'Professor', 'Athabasca University'),
(315, 'Science', 'Sessional', 'NAIT'),
(316, 'Law', 'Sessional', 'Athabasca University'),
(317, 'Science', 'Sessional', 'Athabasca University'),
(318, 'Arts', 'Professor', 'NAIT'),
(319, 'Science', 'Sessional', 'University of Calgary'),
(320, 'Business', 'Sessional', 'NAIT'),
(321, 'Arts', 'Sessional', 'NAIT'),
(322, 'Business', 'Sessional', 'University of Alberta'),
(323, 'Business', 'Associate Professor', 'Athabasca University'),
(324, 'Law', 'Associate Professor', 'University of Alberta'),
(325, 'Law', 'Associate Professor', 'NAIT'),
(326, 'Business', 'Professor', 'University of Calgary'),
(327, 'Science', 'Sessional', 'MacEwan University'),
(328, 'Arts', 'Associate Professor', 'MacEwan University'),
(329, 'Business', 'Sessional', 'Mount Royal University'),
(330, 'Law', 'Professor', 'University of Calgary'),
(331, 'Law', 'Sessional', 'NorQuest College'),
(332, 'Science', 'Associate Professor', 'University of Calgary'),
(333, 'Business', 'Sessional', 'University of Calgary'),
(334, 'Law', 'Sessional', 'NAIT'),
(335, 'Law', 'Professor', 'NAIT'),
(336, 'Science', 'Associate Professor', 'Mount Royal University'),
(337, 'Business', 'Sessional', 'Mount Royal University'),
(338, 'Law', 'Professor', 'University of Calgary'),
(339, 'Business', 'Professor', 'NAIT'),
(340, 'Business', 'Professor', 'University of Calgary'),
(341, 'Science', 'Professor', 'Athabasca University'),
(342, 'Law', 'Sessional', 'MacEwan University'),
(343, 'Science', 'Professor', 'University of Calgary'),
(344, 'Law', 'Professor', 'SAIT'),
(345, 'Science', 'Sessional', 'NorQuest College'),
(346, 'Law', 'Sessional', 'Bow Valley University'),
(347, 'Business', 'Sessional', 'University of Alberta'),
(348, 'Science', 'Sessional', 'University of Alberta'),
(349, 'Arts', 'Sessional', 'MacEwan University'),
(350, 'Law', 'Professor', 'Mount Royal University'),
(351, 'Law', 'Sessional', 'NorQuest College'),
(352, 'Law', 'Professor', 'NAIT'),
(353, 'Business', 'Professor', 'University of Calgary'),
(354, 'Science', 'Associate Professor', 'SAIT'),
(355, 'Arts', 'Sessional', 'Athabasca University'),
(356, 'Arts', 'Associate Professor', 'University of Calgary'),
(357, 'Arts', 'Professor', 'University of Calgary'),
(358, 'Arts', 'Associate Professor', 'University of Alberta'),
(359, 'Business', 'Professor', 'Athabasca University'),
(360, 'Business', 'Associate Professor', 'University of Alberta'),
(361, 'Science', 'Associate Professor', 'Mount Royal University'),
(362, 'Law', 'Sessional', 'Mount Royal University'),
(363, 'Arts', 'Sessional', 'Mount Royal University'),
(364, 'Business', 'Associate Professor', 'NAIT'),
(365, 'Science', 'Sessional', 'University of Alberta'),
(366, 'Law', 'Associate Professor', 'University of Calgary'),
(367, 'Business', 'Sessional', 'University of Calgary'),
(368, 'Law', 'Associate Professor', 'NAIT'),
(369, 'Arts', 'Associate Professor', 'University of Alberta'),
(370, 'Business', 'Professor', 'Mount Royal University'),
(371, 'Law', 'Professor', 'Bow Valley University'),
(372, 'Law', 'Associate Professor', 'SAIT'),
(373, 'Arts', 'Sessional', 'NAIT'),
(374, 'Business', 'Professor', 'MacEwan University'),
(375, 'Science', 'Associate Professor', 'NAIT'),
(376, 'Arts', 'Associate Professor', 'Bow Valley University'),
(377, 'Arts', 'Professor', 'MacEwan University'),
(378, 'Business', 'Sessional', 'Athabasca University'),
(379, 'Science', 'Associate Professor', 'NorQuest College'),
(380, 'Science', 'Associate Professor', 'Athabasca University'),
(381, 'Law', 'Associate Professor', 'University of Calgary'),
(382, 'Arts', 'Professor', 'Athabasca University'),
(383, 'Business', 'Professor', 'Mount Royal University'),
(384, 'Science', 'Associate Professor', 'SAIT'),
(385, 'Business', 'Sessional', 'Bow Valley University'),
(386, 'Science', 'Associate Professor', 'NAIT'),
(387, 'Law', 'Professor', 'Mount Royal University'),
(388, 'Business', 'Sessional', 'SAIT'),
(389, 'Science', 'Associate Professor', 'Mount Royal University'),
(390, 'Arts', 'Sessional', 'Mount Royal University'),
(391, 'Business', 'Associate Professor', 'NAIT'),
(392, 'Science', 'Associate Professor', 'Bow Valley University'),
(393, 'Law', 'Professor', 'Athabasca University'),
(394, 'Law', 'Professor', 'University of Calgary'),
(395, 'Law', 'Associate Professor', 'Athabasca University'),
(396, 'Law', 'Associate Professor', 'NorQuest College'),
(397, 'Law', 'Professor', 'MacEwan University'),
(398, 'Arts', 'Associate Professor', 'NAIT'),
(399, 'Law', 'Professor', 'NorQuest College'),
(400, 'Business', 'Associate Professor', 'NorQuest College'),
(401, 'Law', 'Professor', 'NAIT'),
(402, 'Business', 'Sessional', 'University of Alberta'),
(403, 'Business', 'Sessional', 'Bow Valley University'),
(404, 'Arts', 'Sessional', 'University of Calgary'),
(405, 'Arts', 'Associate Professor', 'Mount Royal University'),
(406, 'Science', 'Professor', 'NorQuest College'),
(407, 'Business', 'Professor', 'University of Calgary'),
(408, 'Business', 'Professor', 'SAIT'),
(409, 'Business', 'Sessional', 'MacEwan University'),
(410, 'Arts', 'Associate Professor', 'NAIT'),
(411, 'Law', 'Associate Professor', 'SAIT'),
(412, 'Arts', 'Professor', 'MacEwan University'),
(413, 'Arts', 'Professor', 'University of Calgary'),
(414, 'Arts', 'Associate Professor', 'University of Alberta'),
(415, 'Arts', 'Associate Professor', 'Bow Valley University'),
(416, 'Law', 'Sessional', 'University of Calgary'),
(417, 'Business', 'Professor', 'NAIT'),
(418, 'Science', 'Professor', 'Athabasca University'),
(419, 'Law', 'Sessional', 'University of Alberta'),
(420, 'Arts', 'Associate Professor', 'MacEwan University'),
(421, 'Arts', 'Sessional', 'NorQuest College'),
(422, 'Science', 'Professor', 'University of Calgary'),
(423, 'Law', 'Sessional', 'NAIT'),
(424, 'Science', 'Associate Professor', 'NorQuest College'),
(425, 'Arts', 'Professor', 'MacEwan University'),
(426, 'Science', 'Professor', 'University of Alberta'),
(427, 'Law', 'Associate Professor', 'Bow Valley University'),
(428, 'Arts', 'Associate Professor', 'University of Calgary'),
(429, 'Law', 'Professor', 'Bow Valley University'),
(430, 'Science', 'Sessional', 'MacEwan University'),
(431, 'Science', 'Sessional', 'NorQuest College'),
(432, 'Arts', 'Professor', 'NorQuest College'),
(433, 'Business', 'Associate Professor', 'SAIT'),
(434, 'Science', 'Sessional', 'Bow Valley University'),
(435, 'Arts', 'Sessional', 'NorQuest College'),
(436, 'Law', 'Associate Professor', 'NAIT'),
(437, 'Law', 'Professor', 'University of Alberta'),
(438, 'Business', 'Associate Professor', 'Mount Royal University'),
(439, 'Law', 'Sessional', 'University of Alberta'),
(440, 'Arts', 'Sessional', 'NAIT'),
(441, 'Law', 'Sessional', 'Athabasca University'),
(442, 'Business', 'Associate Professor', 'MacEwan University'),
(443, 'Science', 'Sessional', 'NorQuest College'),
(444, 'Business', 'Professor', 'Bow Valley University'),
(445, 'Arts', 'Professor', 'University of Alberta'),
(446, 'Law', 'Sessional', 'SAIT'),
(447, 'Science', 'Professor', 'Athabasca University'),
(448, 'Arts', 'Associate Professor', 'Athabasca University'),
(449, 'Law', 'Sessional', 'Athabasca University'),
(450, 'Business', 'Professor', 'Athabasca University'),
(451, 'Science', 'Associate Professor', 'NAIT'),
(452, 'Law', 'Sessional', 'SAIT'),
(453, 'Business', 'Associate Professor', 'NorQuest College'),
(454, 'Law', 'Professor', 'University of Calgary'),
(455, 'Arts', 'Associate Professor', 'SAIT'),
(456, 'Arts', 'Professor', 'Athabasca University'),
(457, 'Law', 'Professor', 'MacEwan University'),
(458, 'Business', 'Sessional', 'Athabasca University'),
(459, 'Science', 'Associate Professor', 'NAIT'),
(460, 'Arts', 'Associate Professor', 'University of Calgary'),
(461, 'Law', 'Professor', 'MacEwan University'),
(462, 'Business', 'Associate Professor', 'University of Calgary'),
(463, 'Law', 'Associate Professor', 'SAIT'),
(464, 'Law', 'Professor', 'NAIT'),
(465, 'Arts', 'Associate Professor', 'Bow Valley University'),
(466, 'Law', 'Sessional', 'NAIT'),
(467, 'Law', 'Professor', 'University of Calgary'),
(468, 'Arts', 'Professor', 'University of Alberta'),
(469, 'Law', 'Professor', 'NorQuest College'),
(470, 'Law', 'Professor', 'University of Calgary'),
(471, 'Law', 'Associate Professor', 'Athabasca University'),
(472, 'Science', 'Associate Professor', 'NAIT'),
(473, 'Business', 'Associate Professor', 'SAIT'),
(474, 'Science', 'Associate Professor', 'Bow Valley University'),
(475, 'Science', 'Sessional', 'Mount Royal University'),
(476, 'Science', 'Professor', 'Athabasca University'),
(477, 'Business', 'Professor', 'SAIT'),
(478, 'Law', 'Sessional', 'Bow Valley University'),
(479, 'Law', 'Sessional', 'SAIT'),
(480, 'Law', 'Associate Professor', 'MacEwan University'),
(481, 'Science', 'Sessional', 'University of Calgary'),
(482, 'Arts', 'Sessional', 'University of Calgary'),
(483, 'Arts', 'Sessional', 'NAIT'),
(484, 'Business', 'Associate Professor', 'MacEwan University'),
(485, 'Law', 'Sessional', 'SAIT'),
(486, 'Arts', 'Associate Professor', 'Athabasca University'),
(487, 'Science', 'Sessional', 'NorQuest College'),
(488, 'Science', 'Sessional', 'MacEwan University'),
(489, 'Law', 'Associate Professor', 'University of Calgary'),
(490, 'Arts', 'Professor', 'MacEwan University'),
(491, 'Arts', 'Sessional', 'NorQuest College'),
(492, 'Arts', 'Professor', 'Mount Royal University'),
(493, 'Science', 'Sessional', 'NorQuest College'),
(494, 'Law', 'Sessional', 'Athabasca University'),
(495, 'Science', 'Associate Professor', 'Athabasca University'),
(496, 'Arts', 'Professor', 'University of Calgary'),
(497, 'Law', 'Sessional', 'University of Calgary'),
(498, 'Business', 'Professor', 'NAIT'),
(499, 'Science', 'Professor', 'NAIT'),
(500, 'Law', 'Sessional', 'NorQuest College'),
(501, 'Science', 'Sessional', 'University of Calgary'),
(502, 'Science', 'Professor', 'University of Calgary'),
(503, 'Law', 'Sessional', 'University of Alberta'),
(504, 'Business', 'Associate Professor', 'Athabasca University'),
(505, 'Arts', 'Sessional', 'SAIT'),
(506, 'Arts', 'Professor', 'MacEwan University'),
(507, 'Law', 'Sessional', 'MacEwan University'),
(508, 'Arts', 'Sessional', 'SAIT'),
(509, 'Business', 'Sessional', 'University of Alberta'),
(510, 'Law', 'Professor', 'NAIT'),
(511, 'Science', 'Professor', 'MacEwan University'),
(512, 'Law', 'Associate Professor', 'Mount Royal University'),
(513, 'Arts', 'Associate Professor', 'Bow Valley University'),
(514, 'Law', 'Professor', 'University of Alberta'),
(515, 'Law', 'Associate Professor', 'Mount Royal University'),
(516, 'Arts', 'Associate Professor', 'Athabasca University'),
(517, 'Arts', 'Associate Professor', 'Bow Valley University'),
(518, 'Law', 'Professor', 'NAIT'),
(519, 'Law', 'Sessional', 'University of Calgary'),
(520, 'Science', 'Associate Professor', 'SAIT'),
(521, 'Arts', 'Associate Professor', 'University of Alberta'),
(522, 'Business', 'Professor', 'SAIT'),
(523, 'Law', 'Professor', 'MacEwan University'),
(524, 'Arts', 'Associate Professor', 'SAIT'),
(525, 'Law', 'Professor', 'Bow Valley University'),
(526, 'Science', 'Professor', 'Mount Royal University'),
(527, 'Business', 'Sessional', 'Mount Royal University'),
(528, 'Law', 'Professor', 'Bow Valley University'),
(529, 'Business', 'Professor', 'SAIT'),
(530, 'Law', 'Professor', 'MacEwan University'),
(531, 'Arts', 'Sessional', 'Athabasca University'),
(532, 'Law', 'Sessional', 'NAIT'),
(533, 'Business', 'Associate Professor', 'MacEwan University'),
(534, 'Arts', 'Sessional', 'University of Calgary'),
(535, 'Law', 'Professor', 'Bow Valley University'),
(536, 'Law', 'Professor', 'University of Alberta'),
(537, 'Law', 'Associate Professor', 'Mount Royal University'),
(538, 'Arts', 'Sessional', 'University of Calgary'),
(539, 'Business', 'Associate Professor', 'Athabasca University'),
(540, 'Arts', 'Sessional', 'Bow Valley University'),
(541, 'Law', 'Sessional', 'NorQuest College'),
(542, 'Science', 'Sessional', 'NorQuest College'),
(543, 'Business', 'Professor', 'Bow Valley University'),
(544, 'Law', 'Professor', 'MacEwan University'),
(545, 'Law', 'Professor', 'NorQuest College'),
(546, 'Arts', 'Professor', 'University of Alberta'),
(547, 'Law', 'Professor', 'NAIT'),
(548, 'Arts', 'Professor', 'Mount Royal University'),
(549, 'Business', 'Associate Professor', 'NAIT'),
(550, 'Law', 'Sessional', 'NAIT'),
(551, 'Science', 'Sessional', 'MacEwan University'),
(552, 'Arts', 'Sessional', 'University of Calgary'),
(553, 'Business', 'Sessional', 'University of Alberta'),
(554, 'Science', 'Associate Professor', 'Bow Valley University'),
(555, 'Law', 'Professor', 'MacEwan University'),
(556, 'Science', 'Professor', 'Bow Valley University'),
(557, 'Business', 'Professor', 'Athabasca University'),
(558, 'Science', 'Associate Professor', 'University of Alberta'),
(559, 'Law', 'Associate Professor', 'Athabasca University'),
(560, 'Law', 'Professor', 'University of Calgary'),
(561, 'Law', 'Associate Professor', 'NAIT'),
(562, 'Business', 'Sessional', 'MacEwan University'),
(563, 'Arts', 'Professor', 'University of Calgary'),
(564, 'Law', 'Professor', 'Mount Royal University'),
(565, 'Arts', 'Sessional', 'University of Calgary'),
(566, 'Arts', 'Professor', 'University of Calgary'),
(567, 'Law', 'Professor', 'NAIT'),
(568, 'Business', 'Associate Professor', 'Bow Valley University'),
(569, 'Science', 'Professor', 'Bow Valley University'),
(570, 'Business', 'Professor', 'University of Calgary'),
(571, 'Law', 'Sessional', 'University of Calgary'),
(572, 'Law', 'Professor', 'University of Alberta'),
(573, 'Science', 'Professor', 'NAIT'),
(574, 'Law', 'Associate Professor', 'NorQuest College'),
(575, 'Business', 'Sessional', 'Mount Royal University'),
(576, 'Business', 'Associate Professor', 'NAIT'),
(577, 'Arts', 'Professor', 'NorQuest College'),
(578, 'Business', 'Professor', 'Athabasca University'),
(579, 'Science', 'Professor', 'Mount Royal University'),
(580, 'Business', 'Sessional', 'MacEwan University'),
(581, 'Law', 'Associate Professor', 'MacEwan University'),
(582, 'Science', 'Associate Professor', 'Mount Royal University'),
(583, 'Science', 'Associate Professor', 'Athabasca University'),
(584, 'Arts', 'Associate Professor', 'SAIT'),
(585, 'Science', 'Associate Professor', 'NAIT'),
(586, 'Arts', 'Associate Professor', 'Mount Royal University'),
(587, 'Business', 'Professor', 'SAIT'),
(588, 'Business', 'Sessional', 'Bow Valley University'),
(589, 'Business', 'Associate Professor', 'Bow Valley University'),
(590, 'Business', 'Professor', 'MacEwan University'),
(591, 'Arts', 'Professor', 'SAIT'),
(592, 'Law', 'Associate Professor', 'University of Alberta'),
(593, 'Law', 'Associate Professor', 'NorQuest College'),
(594, 'Arts', 'Sessional', 'MacEwan University'),
(595, 'Science', 'Associate Professor', 'NAIT'),
(596, 'Law', 'Professor', 'MacEwan University'),
(597, 'Law', 'Professor', 'NAIT');

